AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_MAP_ENABLE = yes
KEYMAP_INTROSPECTION_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
